# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
src/routes/v2/authenticate-schema.yml:
  struct:
    - >-
      #/paths/~1external-auth~1security-answers~1{crn}/get/parameters/0/x-examples
src/routes/v2/organisation-schema.yml:
  struct:
    - '#/paths/~1organisation~1{organisationId}/get/parameters/0/x-examples'
src/routes/v2/person-schema.yml:
  struct:
    - '#/paths/~1person~1{personId}~1summary/get/parameters/0/x-examples'
