# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
src/routes/v2/organisation-schema.yml:
  struct:
    - '#/paths/~1organisation~1{organisationId}/get/parameters/0/example'
src/routes/v2/person-schema.yml:
  struct:
    - '#/paths/~1person~1{personId}~1summary/get/parameters/0/example'
