services:
  # Extends the DAL mock to support client-side MTLS configuration (should be run as part of ./scripts/run-dal-downstream-and-mtls-kits-upstream.sh)
  dal-mock:
    environment:
      KITS_CA_CERT: ${KITS_CA_CERT:?KITS_CA_CERT must be set for kits emulation}
      KITS_INTERNAL_GATEWAY_URL: https://kits-emulation-mock:3101/extapi
      KITS_INTERNAL_CONNECTION_KEY: ${KITS_INTERNAL_CONNECTION_KEY:?KITS_INTERNAL_CONNECTION_KEY must be set}
      KITS_INTERNAL_CONNECTION_CERT: ${KITS_INTERNAL_CONNECTION_CERT:?KITS_INTERNAL_CONNECTION_CERT must be set}
      KITS_EXTERNAL_GATEWAY_URL: https://kits-emulation-mock:3101/extapi
      KITS_EXTERNAL_CONNECTION_KEY: $KITS_INTERNAL_CONNECTION_KEY
      KITS_EXTERNAL_CONNECTION_CERT: $KITS_INTERNAL_CONNECTION_CERT

    volumes:
      - ./scripts/mtls/ca.crt:/tmp/ca.crt:ro
      - ./scripts/mtls/client.crt:/tmp/client.crt:ro
      - ./scripts/mtls/client.key:/tmp/client.key:ro
