swagger: '2.0'
info:
  title: Applications API
  description: API for applications data and related operations
  version: '1.0.0'
  license:
    name: 'Open Government Licence v3.0'
    url: 'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3'
tags:
  - name: 'applications'
    description: 'Operations related to applications management'
schemes:
  - 'http'
security: [] # mTLS, but swagger 2.0 does not support it directly, should probably upgrade to 3.0+
basePath: /extapi
paths:
  /SitiAgriApi/cv/appByBusiness/sbi/{sbi}/list:
    get:
      tags:
        - 'applications'
      summary: 'List Applications for a business.'
      description: 'Gets details for Applications for a business specified by SBI.'
      operationId: 'getApplicationsBySBI'
      produces:
        - 'application/json'
        - 'text/html'
      parameters:
        - name: 'sbi'
          in: 'path'
          description: 'SBI of the business to retrieve applications for.'
          required: true
          type: 'integer'
          maximum: 99999999999999999999
          x-examples: [1000000000, 1111111111, 2222222222]
      responses:
        '200':
          description: 'Returns full organisation details.'
          schema:
            type: 'object'
            properties:
              data:
                type: 'array'
                items:
                  $ref: '#/definitions/Application'
              errorString:
                type: ['string', 'null']
              success:
                type: boolean
            required:
              - data
              - errorString
              - success
        '403':
          description: 'Getting Application details is forbidden, or a WAF rule has been triggered,\
            \ or the SBI was not found (i.e. 404!).'
          examples:
            text/html: |
              <html><body><h1>403 Forbidden</h1>
              Request forbidden by administrative rules.
              </body></html>

definitions:
  Application:
    type: object
    properties:
      sbi:
        type: string
      subject_id:
        type: integer
      year:
        type: integer
      application_name:
        type: string
      module_code:
        type: string
      scheme:
        type: string
      application_id:
        type: integer
      status_code_p:
        type: string
      status_code_s:
        type: string
      status:
        type: string
      submission_date:
        type: ['string', 'null']
      portal_status_p:
        type: string
      portal_status_s:
        type: ['string', 'null']
      portal_status:
        type: ['string', 'null']
      fg_active:
        type: string
      transition_id:
        type: integer
      transition_name:
        type: string
      agreement_ref:
        type: ['string', 'null']
      application_history:
        type: array
        items:
          $ref: '#/definitions/ApplicationHistory'
    required:
      - sbi
      - subject_id
      - year
      - application_name
      - module_code
      - scheme
      - application_id
      - status_code_p
      - status_code_s
      - status
      - submission_date
      - portal_status_p
      - portal_status_s
      - fg_active
      - transition_id
      - transition_name
      - agreement_ref
      - application_history
  ApplicationHistory:
    type: object
    properties:
      dt_transition:
        type: string
      check_status:
        type: string
      transition_id:
        type: integer
      transition_name:
        type: string
    required:
      - dt_transition
      - check_status
      - transition_id
      - transition_name
