---
swagger: "2.0"
info: {}
tags:
- name: "Status"
schemes:
- "http"
paths:
  /answers/{businessId}:
    post:
      summary: "Submits the Countryside stewardship answers"
      description: "Submits the Countryside stewardship answers and returns suggestions\
        \ regarding the available options"
      operationId: "postAnswers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "callerId"
        in: "header"
        required: false
        type: "integer"
      - name: "userType"
        in: "header"
        required: false
        type: "string"
      - name: "businessId"
        in: "path"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/AnswersRequest"
      responses:
        "200":
          description: "Suggestions regarding the available options to apply to"
          schema:
            $ref: "#/definitions/Response"
  /answersWithNca/{businessId}:
    post:
      summary: "Submits the Countryside stewardship answers with the National Character\
        \ Area"
      description: "Submits the Countryside stewardship answers with the National\
        \ Character Area and returns suggestions regarding the available options"
      operationId: "postAnswersWithNca"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "callerId"
        in: "header"
        required: false
        type: "integer"
      - name: "userType"
        in: "header"
        required: false
        type: "string"
      - name: "businessId"
        in: "path"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/AnswersWithNcaRequest"
      responses:
        "200":
          description: "Suggestions regarding the available options to apply to"
          schema:
            $ref: "#/definitions/Response"
  /reloadDatabase:
    get:
      summary: "Reload DB content"
      description: "Replaces current DB content (config and options for CS Tool) with\
        \ data parsed from CSV files."
      operationId: "reloadDatabaseContent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "DB content reloaded successfully"
          schema:
            $ref: "#/definitions/Response"
  /reloadCache:
    get:
      summary: "Reload  NCA, Options and Configuration Matrix caches"
      description: "Reload NCA, Options and Configuration Matrix caches from the database"
      operationId: "reloadCache"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Caches reloaded successfully"
          schema:
            $ref: "#/definitions/Response"
  /nca/{businessId}:
    get:
      summary: "Replaces current DB content"
      description: "Replaces current DB content (config and options for CS Tool) with\
        \ data parsed from CSV files."
      operationId: "getBusinessNcas"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "callerId"
        in: "header"
        required: false
        type: "integer"
      - name: "userType"
        in: "header"
        required: false
        type: "string"
      - name: "businessId"
        in: "path"
        required: true
        type: "integer"
      responses:
        "200":
          description: "DB content replaced"
          schema:
            $ref: "#/definitions/Response"
  /status:
    get:
      tags:
      - "Status"
      summary: "Application Healthcheck"
      description: "Checks service health."
      operationId: "getStatus"
      produces:
      - "text/plain"
      parameters: []
      responses:
        "200":
          description: "Application health status"
definitions:
  EntityTag:
    type: "object"
    properties:
      value:
        type: "string"
      weak:
        type: "boolean"
  Link:
    type: "object"
    properties:
      type:
        type: "string"
      title:
        type: "string"
      uri:
        type: "string"
        format: "uri"
      uriBuilder:
        $ref: "#/definitions/UriBuilder"
      rel:
        type: "string"
      rels:
        type: "array"
        items:
          type: "string"
      params:
        type: "object"
        additionalProperties:
          type: "string"
  Locale:
    type: "object"
    properties:
      displayName:
        type: "string"
      script:
        type: "string"
      country:
        type: "string"
      variant:
        type: "string"
      extensionKeys:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      unicodeLocaleAttributes:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      unicodeLocaleKeys:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      iso3Language:
        type: "string"
      iso3Country:
        type: "string"
      displayLanguage:
        type: "string"
      displayScript:
        type: "string"
      displayCountry:
        type: "string"
      displayVariant:
        type: "string"
      language:
        type: "string"
  MediaType:
    type: "object"
    properties:
      type:
        type: "string"
      subtype:
        type: "string"
      parameters:
        type: "object"
        additionalProperties:
          type: "string"
      wildcardSubtype:
        type: "boolean"
      wildcardType:
        type: "boolean"
  NewCookie:
    type: "object"
    properties:
      name:
        type: "string"
      value:
        type: "string"
      version:
        type: "integer"
        format: "int32"
      path:
        type: "string"
      domain:
        type: "string"
      comment:
        type: "string"
      maxAge:
        type: "integer"
        format: "int32"
      expiry:
        type: "string"
        format: "date-time"
      secure:
        type: "boolean"
      httpOnly:
        type: "boolean"
  Response:
    type: "object"
    properties:
      lastModified:
        type: "string"
        format: "date-time"
      date:
        type: "string"
        format: "date-time"
      length:
        type: "integer"
        format: "int32"
      location:
        type: "string"
        format: "uri"
      language:
        $ref: "#/definitions/Locale"
      entity:
        type: "object"
      status:
        type: "integer"
        format: "int32"
      metadata:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            type: "object"
      allowedMethods:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      cookies:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/NewCookie"
      statusInfo:
        $ref: "#/definitions/StatusType"
      entityTag:
        $ref: "#/definitions/EntityTag"
      mediaType:
        $ref: "#/definitions/MediaType"
      links:
        type: "array"
        uniqueItems: true
        items:
          $ref: "#/definitions/Link"
      stringHeaders:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            type: "string"
      headers:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            type: "object"
  StatusType:
    type: "object"
    properties:
      family:
        type: "string"
        enum:
        - "INFORMATIONAL"
        - "SUCCESSFUL"
        - "REDIRECTION"
        - "CLIENT_ERROR"
        - "SERVER_ERROR"
        - "OTHER"
      statusCode:
        type: "integer"
        format: "int32"
      reasonPhrase:
        type: "string"
  UriBuilder:
    type: "object"
  AnswersRequest:
    type: "object"
    properties:
      answers:
        type: "object"
        additionalProperties:
          type: "boolean"
  AnswersWithNcaRequest:
    type: "object"
    properties:
      answers:
        type: "object"
        additionalProperties:
          type: "boolean"
      nca:
        type: "array"
        items:
          type: "string"