name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install, lint, & test
        run: npm cit

      - name: Test Docker Image Build
        run: docker build --no-cache --tag fcp-dal-upstream-mock .
