name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Audit, install, lint, & test
        run: |
          npm audit --omit=dev
          npm ci
          npm run lint
          npm t

      - name: Docker build, Contract test
        run: >
          docker compose \
            -f compose.yml \
            -f test/contract/compose.yml \
            run --build --quiet-pull --pull always --rm contract-tests
